title: Mark Zakharov
description: CPU Engineer, open-srouce advocate, RISC-V nerd, overall nerd, musician, frog father (in that order)
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
